//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finall_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryData
    {
        public decimal BOOK_ID { get; set; }
        public string BOOK_NAME { get; set; }
        public decimal NUM_OF_BOOK { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
